---
- name: Install apt-upgrade-report helper
  when: ansible_facts['system'] == 'Linux'
  become: true
  ansible.builtin.template:
    src: apt-upgrade-report.j2
    dest: /usr/local/bin/apt-upgrade-report
    mode: "0755"

